
// b!alt_02.baf - because berelinde is an idiot

IF
    True()
THEN 
    RESPONSE #100 
      CutSceneId(Player1)
      FadeToColor([20.0],0)
      Wait(1)
      ActionOverride("b!prelat",DestroySelf()) 
      ActionOverride("b!brega",DestroySelf())
      RestorePartyLocations() 
      MoveViewObject(Player1,INSTANT) 
      FadeFromColor([20.0],0)
      Wait(1)
      EndCutSceneMode()
END 
